sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO:$COMMIT

