# ------------------- Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubetor
spec:
  strategy:
    type: RollingUpdate
  replicas: 14
  template:
    metadata:
      labels:
        app: kubetor
    spec:
      containers:
      - name: kubetor
        image: "k8sutils/kubetor:GITVERSION"
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 9050
          initialDelaySeconds: 1
          periodSeconds: 10
        env:
        - name: TORUSER #If set use named user instead of 'tor' (for example root)
          value: ""
        - name: BW # As above, set a tor relay bandwidth limit in KB, IE 50
          value: ""
        - name: EXITNODE # As above, allow tor traffic to access the internet from your IP
          value: ""
        - name: LOCATION # As above, configure the country to use for exit node selection
          value: ""
        - name: PASSWORD # As above, configure HashedControlPassword for control port 
          value: ""
        - name: TZ # Configure the zoneinfo timezone, IE EST5EDT
          value: ""
        - name: USERID # Set the UID for the app user
          value: ""
        - name: GROUPID # Set the GID for the app user
          value: ""
        ports:
        - name: socks
          protocol: TCP
          containerPort: 9050
---
# ------------------- Service Load Balancer ------------------- #
apiVersion: v1
kind: Service
metadata:
  name: kubetor
  labels:
    app: kubetor
spec:
  ports:
  - name: socks
    port: 443
    targetPort: 9050
    protocol: TCP
  selector:
    app: kubetor
  type: LoadBalancer
